spring:
  profiles:
    include: dev
server:
  servlet:
    context-path: /api

app:
  websocket:
    allowed-origins:
      - "*"
  timetable:
      generation-job-cron: "0 0 */1 * * *"
  ticket:
      status-update-job-cron: "*/10 * * * * *"
